version: '3.9'

services:

  simple-api-gateway:
    build: .
    restart: always
    # ports:
    # - "4000:4000"
    # - "50051:50051"
    # - "50052:50052"
    # - "50053:50053"
    # - "50054:50054"
    # - "50055:50055"
    # - "27017:27017"
    # - "5432:5432"
    depends_on:
      - grpc-mail
      - redis
      - mongodb
      - db
      - grpc-admin
      - grpc-user
      - grpc-orders
      - grpc-product
      - grpc-balance
  grpc-user:
    build: ../grpc-jwt-login
    container_name: grpc-jwt-login
    restart: always
    ports:
      - "50052:50052"
    depends_on:
      - grpc-admin
  grpc-admin:
    build: ../grpc-admin
    container_name: grpc-admin
    restart: always
    ports:
      - "50051:50051"
    depends_on:
      - db

  grpc-mail:
    build: ../grpc-mail
    container_name: grpc-mail
    restart: always
    ports:
      - 50053:50053
      - 3003:3003
    depends_on:
      - grpc-user
  
  grpc-product:
    build: ../grpc-product
    container_name: grpc-product
    restart: always
    ports:
      - 50054:50054
    depends_on:
      - grpc-user
      - grpc-admin
      - grpc-mail
  grpc-orders:
    build: ../grpc-orders
    container_name: grpc-orders
    restart: always
    ports: 
      - 50055:50055
    depends_on:
      - grpc-user
      - grpc-admin
      - grpc-mail
  grpc-balance:
    build: ../grpc-balance
    container_name: grpc-balance
    restart: always
    ports: 
      - 50056:50056
    depends_on:
      - grpc-user
      - grpc-admin
      - grpc-mail
  concurrency-example:
    build: ../concurrency-example
    container_name: concurrency-example
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - simple-api-gateway
  
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wallets
      - MONGO_INITDB_ROOT_PASSWORD=wallets
    volumes:
      - ../simple-api-gateway-data/mongo:/data/db
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=1234

  db:
    image: postgres:15.2-alpine3.17
    container_name: db
    environment:
      POSTGRES_PASSWORD: api-gateway
      POSTGRES_USER: api-gateway
      POSTGRES_DB: api-gateway

    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api-gateway"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ../simple-api-gateway-data/postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - simple-api-gateway